export const STARTING_PLAYER_HEALTH = 10;
export const STARTING_ENEMY_HEALTH = 10;
export const DESKTOP_BREAK_POINT = 1000;

export const textMap = {
  START_GAME: "PRESS ATTACK TO START",
  PLAYER_HIT: "YOU HIT FOR ",
  ENEMY_HIT: "ENEMY HIT YOU FOR ",
  DRAW_HIT: "NEITHER PLAYER TOOK DAMAGE",
  DICE_ROLLING: "ROLLING DICE",
  PLAYER_WIN: "YOU WIN",
  ENEMY_WIN: "GAME OVER",
};
